platform :ios, "16.0"
use_frameworks!

@checksum = "dummy-checksum-to-prevent-merge-conflicts"

plugin "{{name}}"

config_compact_spec(
  extra: ->(s) { s.ios.deployment_target = "16.0" }
)

target "EX" do
  # Code goes here
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete "IPHONEOS_DEPLOYMENT_TARGET"
    end
  end
end
