exclude: ^(VERSION)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/rubocop/rubocop
    rev: v1.58.0
    hooks:
      - id: rubocop
  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.52.11
    hooks:
      - id: swiftformat
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: ['-r', '-i', '--remove-all-unused-imports', '--remove-unused-variables']
        exclude: __init__.py$
