AllCops:
  NewCops: enable
  SuggestExtensions: false
  Include:
    - lib/**/*.rb
    - spec/**/*.rb
  Exclude:
    - spec/spec_helper.rb

Gemspec/RequiredRubyVersion:
  Enabled: false
Gemspec/RequireMFA:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/cocoapods-spm.rb

Metrics/AbcSize:
  Enabled: false

Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
Style/WordArray:
  Enabled: false
