AllCops:
  NewCops: enable
  SuggestExtensions: false
  Include:
    - lib/**/*.rb
    - spec/**/*.rb
  Exclude:
    - spec/spec_helper.rb # From CocoaPods's plugin templates

Gemspec/RequiredRubyVersion:
  Enabled: false
Gemspec/RequireMFA:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/FileName:
  Exclude:
    - '**/{Gem,Pod,Fast,Danger,Deliver,Guard,Snap}file'
    - '**/cocoapods-*.rb'

Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
Style/WordArray:
  Enabled: false
